version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: saas_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/ssl
    depends_on:
      - client_saas

  client_saas:
    image: saas:prod
    container_name: saas_app_client
    restart: always
    environment:
      NODE_ENV: production
      APP_NAME: saas_app_client
    expose:
      - "5000"
