version: "3.9"
services:
  app:
    image: multi:prod
    # build: ./app
    container_name: saas_app
    ports:
      - "5000:5000"
    restart: always
    environment:
      NODE_ENV: production
      APP_NAME: API_SERVER

  nginx:
    build: ./nginx
    container_name: saas_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/ssl/certs
